/*
 * lib/field-crypto — envelope encryption with an asymmetric break-glass path.
 *
 * ─── WHAT THESE TESTS ARE FOR ──────────────────────────────────────────────
 *
 * Six properties. The first is the one that matters most, and it is the only
 * one whose failure would be INVISIBLE in production:
 *
 *   1. NO PLAINTEXT FALLBACK, EVER. With either key missing, short or malformed,
 *      every write throws and every read refuses. A helper that quietly stored
 *      the raw account number during a config outage would pass every other
 *      test in this file, ship green, and leave those rows readable in the
 *      column forever — there is no later migration that un-leaks a dump.
 *
 *   2. THE SEAL IS OPTIONAL, AND OPTIONAL IS NOT BEST-EFFORT. This system runs
 *      with ONE key by the owner's decision, so a write with NO recovery key
 *      configured produces a SELF-DESCRIBING UNSEALED envelope rather than
 *      throwing. The distinction that matters, and the one pinned hardest below:
 *      a recovery key that IS configured and then FAILS to seal must still
 *      throw. "None configured" is the only permitted no-seal case — anything
 *      else would silently drop a break-glass path in an environment that has
 *      one, and nothing downstream could ever tell the two apart.
 *      The corollary is pinned too: an unsealed row is not a dead end. It can be
 *      given a seal later with only the OPERATIONAL key.
 *
 *   3. THE RECOVERY PATH ACTUALLY WORKS, WITH ONLY THE PRIVATE KEY. Decrypting
 *      with the operational key absent or wrong is the entire promise of the
 *      design; a break-glass path that has never been exercised is a rumour.
 *
 *   4. A TAMPERED VALUE IS REJECTED, NOT DECODED — at every layer. GCM's tag is
 *      why this is not CBC: an altered value, IV, tag or WRAPPED DEK must throw,
 *      never decrypt into plausible garbage that a payout run would treat as an
 *      account number. An altered SEALED DEK must fail the recovery path.
 *
 *   5. RE-KEYING NEVER TOUCHES THE VALUE CIPHERTEXT. Both re-key primitives
 *      leave the value's iv/tag/ct byte-identical, which is the property that
 *      makes a bulk re-key safe to interrupt.
 *
 *   6. THE MASKS LEAK NEITHER THE VALUE NOR THE CIPHERTEXT, and refuse a
 *      ciphertext outright rather than rendering '••••cGVy'.
 *
 * Pure functions — no DB, no network, nothing written anywhere. The recovery-key
 * store is injected as a plain object (see `store()` below), which is exactly
 * why lib/field-crypto takes a `runner` rather than knowing a table name.
 *
 * KEYPAIRS ARE GENERATED HERE, AT TEST TIME, AND ARE THROWAWAY. The real
 * recovery keypair is generated by the owner in a browser and its private half
 * never touches a server, a repo or an agent — see .env.example.
 *
 * `node --test` runs each test FILE in its own process, so the env manipulation
 * below cannot reach another suite.
 *
 * Runner: `npm test` (node --test --test-force-exit).
 */

const { test } = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('crypto');

/* RSA-2048 for the test corpus, not 4096: this file generates several keypairs
 * and 4096-bit generation costs seconds each, which would make the suite slow
 * enough that someone stops running it. The CODE is size-agnostic (it validates
 * a floor of 2048 and derives every length from the key), and the one place the
 * size matters — the VARCHAR arithmetic — is asserted against a real 4096-bit
 * envelope in its own test below. */
function newRecoveryKeypair(modulusLength = 2048) {
  return crypto.generateKeyPairSync('rsa', {
    modulusLength,
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  });
}

const KEY = crypto.randomBytes(32).toString('base64');
const RECOVERY = newRecoveryKeypair();

process.env.EASYFIX_FIELD_ENC_KEY = KEY;
process.env.EASYFIX_FIELD_RECOVERY_PUBLIC_KEY =
  Buffer.from(RECOVERY.publicKey).toString('base64');

const {
  encryptField, decryptField, isEncrypted, maskAccountNumber, maskName,
  recoverField, rewrapField, rewrapToOperationalKey, resealToRecoveryKey,
  sealToRecoveryKey, resolveRecoveryPublicKey, recoveryKeyByFingerprint,
  NO_SEAL,
} = require('../lib/field-crypto');

const ACCOUNT = '50100123456789';
const HOLDER = 'Priya Sharma';

/* The fingerprints the module stamps, computed independently here rather than
 * read back out of an envelope — so a test asserting "this row names key A"
 * cannot be satisfied by a module that stamps a constant. */
const fpOf = (b64) => crypto.createHash('sha256')
  .update(Buffer.from(b64, 'base64')).digest('hex').slice(0, 8);

const fpOfPublic = (pem) => crypto.createHash('sha256')
  .update(crypto.createPublicKey(pem).export({ type: 'spki', format: 'der' }))
  .digest('hex').slice(0, 8);

const parts = (envelope) => envelope.split(':');
/* The three fields a re-key must never touch: the value's iv, tag and
 * ciphertext — the last three of the ten. */
const valueCiphertext = (envelope) => parts(envelope).slice(-3).join(':');

/* Run `fn` with EASYFIX_FIELD_ENC_KEY set to `value` (undefined = unset), then
 * put the real key back whatever happens. */
async function withKey(value, fn) {
  const saved = process.env.EASYFIX_FIELD_ENC_KEY;
  if (value === undefined) delete process.env.EASYFIX_FIELD_ENC_KEY;
  else process.env.EASYFIX_FIELD_ENC_KEY = value;
  try {
    await fn();
  } finally {
    process.env.EASYFIX_FIELD_ENC_KEY = saved;
  }
}

/* The same for the recovery public key. Takes a PEM and base64s it, or
 * undefined to unset, or a raw string to test a malformed value. */
async function withRecoveryPublic(value, fn) {
  const saved = process.env.EASYFIX_FIELD_RECOVERY_PUBLIC_KEY;
  if (value === undefined) delete process.env.EASYFIX_FIELD_RECOVERY_PUBLIC_KEY;
  else if (value.includes('-----BEGIN')) {
    process.env.EASYFIX_FIELD_RECOVERY_PUBLIC_KEY = Buffer.from(value).toString('base64');
  } else process.env.EASYFIX_FIELD_RECOVERY_PUBLIC_KEY = value;
  try {
    await fn();
  } finally {
    process.env.EASYFIX_FIELD_RECOVERY_PUBLIC_KEY = saved;
  }
}

/* A recovery-key STORE, as a plain object. This is the whole `runner` contract:
 * two async lookups returning rows. No table, no pool, no migration — which is
 * the point of lib/field-crypto not knowing where the key lives. */
function store(rows) {
  return {
    activeRecoveryKey: async () => rows.find((r) => r.active) || null,
    recoveryKeyByFingerprint: async (fp) => rows.find((r) => r.fingerprint === fp) || null,
  };
}

/* Put the module's cached "active recovery key" back to the env one. Every test
 * that primes from a store must call this, because the cache is module-level by
 * design (encryptField is synchronous and cannot await a lookup). */
const resetRecoveryToEnv = () => resolveRecoveryPublicKey(null);

// ═══════════════════════════════════════════════════════════════════════
// 1. ROUND TRIP AND ENVELOPE SHAPE
// ═══════════════════════════════════════════════════════════════════════

test('a value round-trips through encrypt → decrypt unchanged', () => {
  const ct = encryptField(ACCOUNT);
  assert.notEqual(ct, ACCOUNT);
  assert.equal(decryptField(ct), ACCOUNT);
  assert.equal(decryptField(encryptField(HOLDER)), HOLDER);
  // Unicode survives — a holder name is not guaranteed to be ASCII.
  assert.equal(decryptField(encryptField('Zoë D’Souza')), 'Zoë D’Souza');
  assert.equal(decryptField(encryptField('प्रिया शर्मा')), 'प्रिया शर्मा');
});

test('the envelope is v2 with TEN fields and TWO fingerprints', () => {
  const a = encryptField(ACCOUNT);
  const b = encryptField(ACCOUNT);
  for (const ct of [a, b]) {
    const p = parts(ct);
    assert.equal(p.length, 10, 'ten colon-separated fields');
    assert.equal(p[0], 'v2', 'the version prefix is what lets a v3 reader dispatch per row');
    assert.match(p[1], /^[0-9a-f]{8}$/, 'the OPERATIONAL key fingerprint');
    assert.equal(p[1], fpOf(KEY), 'and it names THIS key, computed independently');
    assert.match(p[2], /^[0-9a-f]{8}$/, 'the RECOVERY key fingerprint');
    assert.equal(p[2], fpOfPublic(RECOVERY.publicKey), 'and it names THIS recovery key');
    assert.equal(Buffer.from(p[3], 'base64').length, 12, 'the wrapped DEK gets a 96-bit GCM IV');
    assert.equal(Buffer.from(p[4], 'base64').length, 16, 'and keeps its auth tag');
    assert.equal(Buffer.from(p[5], 'base64').length, 32, 'the wrapped DEK is 32 bytes');
    assert.equal(Buffer.from(p[6], 'base64').length, 256, 'sealed to a 2048-bit key');
    assert.equal(Buffer.from(p[7], 'base64').length, 12, 'the value gets its own fresh IV');
    assert.equal(Buffer.from(p[8], 'base64').length, 16, 'and its own tag');
  }
  // Same plaintext, different everything. A deterministic scheme would let
  // anyone with table access see WHICH employees share an account number
  // without decrypting a thing. The two fingerprints are the only deterministic
  // parts, and that is fine — they name keys, not values.
  assert.notEqual(a, b);
  assert.equal(decryptField(a), decryptField(b));
});

test('TWO VALUES NEVER SHARE A DEK', () => {
  /*
   * A shared DEK would make the whole column one blast radius: unseal one row's
   * data key and you hold every row's. It would also make the wrapped-DEK field
   * a correlation oracle — equal wrapped DEKs would betray which employees were
   * written in the same batch — even before anything is decrypted.
   */
  const wrappedDeks = new Set();
  const sealedDeks = new Set();
  for (let i = 0; i < 200; i += 1) {
    const p = parts(encryptField(ACCOUNT));   // the SAME plaintext every time
    wrappedDeks.add(p[5]);
    sealedDeks.add(p[6]);
  }
  assert.equal(wrappedDeks.size, 200, 'every wrapped data key is distinct');
  assert.equal(sealedDeks.size, 200, 'and so is every sealed one');
});

test('the fingerprints are NOT key material', () => {
  const [, opFp, recFp] = parts(encryptField(ACCOUNT));
  // A 32-bit hash prefix cannot be walked back to a key. The assertion that
  // matters operationally is the weaker, checkable one: the stamp is not a
  // slice of the key, in either encoding.
  assert.equal(KEY.includes(opFp), false, 'not a substring of the base64 key');
  assert.equal(Buffer.from(KEY, 'base64').toString('hex').includes(opFp), false,
    'not a substring of the hex key');
  assert.equal(RECOVERY.publicKey.includes(recFp), false, 'not a substring of the PEM');
  assert.notEqual(opFp, recFp, 'two different keys, two different names');
});

test('the recovery fingerprint is over the DER, so PEM formatting cannot change it', () => {
  /*
   * The same key arrives base64'd from env, as raw PEM from a store row, and as
   * a KeyObject from a caller. A fingerprint that moved with line-wrapping or
   * trailing whitespace would orphan every row on a re-import of the same key.
   */
  const expected = fpOfPublic(RECOVERY.publicKey);
  const mangled = `\n  ${RECOVERY.publicKey.trim().replace(/\n/g, '\r\n')}  \n`;
  return withRecoveryPublic(mangled, () => {
    assert.equal(parts(encryptField(ACCOUNT))[2], expected);
  });
});

test('isEncrypted recognises the envelope and nothing else', () => {
  assert.equal(isEncrypted(encryptField(ACCOUNT)), true);
  const real = encryptField(ACCOUNT);
  for (const notCt of [ACCOUNT, HOLDER, '', null, undefined, 42, {},
    'v3:a:b:c', 'v2:only:three', 'v2::a:b',
    // Fingerprint fields that are not 8 lowercase hex are not fingerprints.
    `v2:ZZZZZZZZ:${parts(real).slice(2).join(':')}`,
    `v2:abc:${parts(real).slice(2).join(':')}`,
    `v2:${parts(real)[1].toUpperCase()}:${parts(real).slice(2).join(':')}`,
    // Nine fields — one short. The pre-addendum shape, with a single
    // fingerprint. It cannot be read: there is no way to know which recovery
    // key its sealed DEK belongs to, which is exactly why the field was added.
    [parts(real)[0], parts(real)[1], ...parts(real).slice(3)].join(':')]) {
    assert.equal(isEncrypted(notCt), false, `${JSON.stringify(notCt)} is not an envelope`);
  }
});

test('a blank encrypts to null and decrypts to null — but the KEYS are still checked', () => {
  for (const blank of [null, undefined, '']) {
    assert.equal(encryptField(blank), null);
    assert.equal(decryptField(blank), null);
  }
  // The gate must not be skippable by passing a blank: if the key check ran
  // AFTER the blank short-circuit, "encrypt every field" would silently become
  // "encrypt every field that happened to be filled in".
  return withKey(undefined, () => {
    assert.throws(() => encryptField(''), (e) => e.code === 'FIELD_ENC_UNAVAILABLE');
    assert.throws(() => decryptField(''), (e) => e.code === 'FIELD_ENC_UNAVAILABLE');
    // The RECOVERY key is a different matter: absent is a supported
    // configuration, so a blank is simply a blank. The operational gate above is
    // the one a blank must not be able to skip.
    return withKey(KEY, () => withRecoveryPublic(undefined, () => {
      assert.equal(encryptField(''), null);
    }));
  });
});

test('an already-encrypted value is not double-wrapped', () => {
  const once = encryptField(ACCOUNT);
  assert.equal(encryptField(once), once);
});

// ═══════════════════════════════════════════════════════════════════════
// 2. FAIL CLOSED — THE PROPERTY THIS FILE EXISTS FOR
// ═══════════════════════════════════════════════════════════════════════

test('a MISSING operational key throws on write and refuses on read', async () => {
  const ct = encryptField(ACCOUNT);
  await withKey(undefined, () => {
    let stored;
    assert.throws(
      () => { stored = encryptField(ACCOUNT); },
      (e) => e.code === 'FIELD_ENC_UNAVAILABLE',
      'a write with no key must throw',
    );
    // THE assertion. Not "it threw" — "it produced nothing that could be
    // stored". A helper that returned the plaintext, or returned it alongside a
    // warning, would satisfy a weaker check and leak in production.
    assert.equal(stored, undefined, 'nothing storable may come back');

    assert.throws(() => decryptField(ct), (e) => e.code === 'FIELD_ENC_UNAVAILABLE',
      'a read with no key must refuse');
  });
  // The key came back, so the outage was an outage and not corruption.
  assert.equal(decryptField(ct), ACCOUNT);
});

test('a SHORT or MALFORMED operational key is treated exactly like a missing one', async () => {
  const ct = encryptField(ACCOUNT);
  const badKeys = {
    'empty string': '',
    'whitespace only': '   ',
    '16 bytes (AES-128)': crypto.randomBytes(16).toString('base64'),
    '31 bytes (one short)': crypto.randomBytes(31).toString('base64'),
    '64 bytes (two keys pasted)': crypto.randomBytes(64).toString('base64'),
    'hex, not base64': crypto.randomBytes(32).toString('hex'),
    'not base64 at all': 'this is not a key!!',
  };
  for (const [label, value] of Object.entries(badKeys)) {
    // eslint-disable-next-line no-await-in-loop -- each case must run with the
    // env set to exactly its own value; running them concurrently would race.
    await withKey(value, () => {
      assert.throws(() => encryptField(ACCOUNT), (e) => e.code === 'FIELD_ENC_UNAVAILABLE',
        `write with ${label} must throw`);
      assert.throws(() => decryptField(ct), (e) => e.code === 'FIELD_ENC_UNAVAILABLE',
        `read with ${label} must refuse`);
    });
  }
});

test('NO recovery key configured is a SUPPORTED write — an unsealed envelope, not an outage', async () => {
  /*
   * THE OWNER'S DECISION, PINNED. One key, no recovery keypair anywhere. An
   * earlier build refused every write in this state, which turned the chosen
   * configuration into an outage.
   *
   * What must hold instead: the write succeeds, the value round-trips, and the
   * envelope SAYS SO — a sentinel where the recovery fingerprint goes and an
   * empty sealed field. Nothing is silently missing; the row describes itself.
   */
  const sealedCt = encryptField(ACCOUNT);
  await withRecoveryPublic(undefined, () => {
    const ct = encryptField(ACCOUNT);
    assert.equal(typeof ct, 'string', 'a write with no recovery key must SUCCEED');
    assert.equal(decryptField(ct), ACCOUNT, 'and round-trip on the operational key');

    const p = parts(ct);
    assert.equal(p.length, 10, 'still ten fields — the grammar did not change');
    assert.equal(p[0], 'v2', 'still v2');
    assert.equal(p[1], fpOf(KEY), 'still names the operational key');
    assert.equal(p[2], NO_SEAL, 'the recovery slot carries the sentinel');
    assert.equal(p[6], '', 'and the sealed DEK is empty');
    // The wrap and the value are untouched by the absence — same lengths as ever.
    assert.equal(Buffer.from(p[5], 'base64').length, 32, 'the DEK is still wrapped');
    assert.equal(Buffer.from(p[7], 'base64').length, 12);

    // Reads of rows written EARLIER, when a key WAS configured, keep working —
    // the recovery key is a write-side input and never a read-side one.
    assert.equal(decryptField(sealedCt), ACCOUNT);
  });
});

test('the unsealed sentinel PARSES, and cannot be confused with a truncated envelope', async () => {
  /*
   * The reason the shape is `-` plus an EMPTY field rather than just a dropped
   * field. A parser must be able to tell "written with no recovery key" from
   * "this row lost a field somewhere", because the first is normal and the
   * second is corruption, and treating either as the other is how a bad row
   * gets written or a good one gets refused.
   */
  let unsealed;
  await withRecoveryPublic(undefined, () => { unsealed = encryptField(ACCOUNT); });
  const p = parts(unsealed);

  assert.equal(isEncrypted(unsealed), true, 'the unsealed shape is a valid envelope');

  // The two halves are pinned to EACH OTHER. Either alone is corruption.
  assert.equal(isEncrypted([...p.slice(0, 2), fpOf(KEY), ...p.slice(3)].join(':')), false,
    'a real fingerprint with an EMPTY seal is refused — that is a row that lost its seal');
  const sealedReal = parts(encryptField(ACCOUNT));
  assert.equal(isEncrypted([...sealedReal.slice(0, 2), NO_SEAL, ...sealedReal.slice(3)].join(':')),
    false, 'and the sentinel with a seal ATTACHED is refused too');

  // Nine fields — the field genuinely dropped rather than emptied.
  assert.equal(isEncrypted([...p.slice(0, 6), ...p.slice(7)].join(':')), false,
    'a truncated envelope must NOT read as unsealed');
  assert.throws(() => decryptField([...p.slice(0, 6), ...p.slice(7)].join(':')),
    (e) => e.code === 'FIELD_ENC_UNAVAILABLE');

  // And the sentinel is not a fingerprint anyone could collide with.
  assert.equal(NO_SEAL, '-');
  assert.equal(/^[0-9a-f]{8}$/.test(NO_SEAL), false);
});

test('a CONFIGURED recovery key that FAILS TO SEAL throws — the seal is optional, not best-effort', async () => {
  /*
   * THE most important assertion in this change, and the one a lazy
   * implementation gets wrong. Making the seal optional is one line away from
   * making it best-effort: wrap the publicEncrypt in a try/catch, fall back to
   * the sentinel, and every write in an environment WITH a recovery key quietly
   * loses its break-glass path the day the key develops a problem — indexed by
   * nothing, discovered on the day it matters, indistinguishable from the rows
   * that were never meant to have one.
   *
   * So: a key that passes validation and then cannot encrypt must THROW. Built
   * as a KeyObject-shaped stand-in that satisfies every check the module makes
   * (public, RSA, 4096-bit, exports DER for the fingerprint) and then fails
   * inside crypto.publicEncrypt, which is exactly the shape of the failure that
   * a catch would swallow.
   */
  const brokenKey = {
    type: 'public',
    asymmetricKeyType: 'rsa',
    asymmetricKeyDetails: { modulusLength: 4096 },
    export: () => Buffer.from('not-a-real-spki-but-fingerprintable'),
  };
  await resolveRecoveryPublicKey(store([{ public_key: brokenKey, active: true }]));
  try {
    let stored;
    assert.throws(
      () => { stored = encryptField(ACCOUNT); },
      // Not a FIELD_ENC_UNAVAILABLE necessarily — it is whatever the crypto
      // layer raised. The assertion is that it PROPAGATED.
      (e) => e instanceof Error,
      'a configured key that cannot seal must throw, never fall back to unsealed',
    );
    assert.equal(stored, undefined, 'and nothing storable may come back');
  } finally {
    await resetRecoveryToEnv();
  }
});

test('a MALFORMED recovery public key is treated exactly like a missing one', async () => {
  const ed25519 = crypto.generateKeyPairSync('ed25519', {
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  }).publicKey;
  const weakRsa = newRecoveryKeypair(1024).publicKey;

  /*
   * A key that is PRESENT and unusable is a fault and still refuses every write.
   * That is what keeps "the seal is optional" from meaning "the seal is
   * best-effort": the only no-seal case is NOTHING CONFIGURED, which is the
   * blank checked separately below.
   */
  const bad = {
    'not base64 at all': 'this is not a key!!',
    'base64 of nonsense': Buffer.from('hello there').toString('base64'),
    // Parses perfectly and then cannot seal — the confusing failure this
    // rejects up front rather than at publicEncrypt.
    'an ed25519 key': ed25519,
    // 1024-bit RSA works. That is the problem: it would silently become the
    // weakest link in a design whose entire job is to be the last one standing.
    'a 1024-bit RSA key': weakRsa,
    /*
     * THE PRIVATE HALF. This is the one that must not be allowed to "work", and
     * it very nearly does: crypto.createPublicKey() ACCEPTS a private PEM and
     * derives the public half from it. Without an explicit refusal, pasting the
     * recovery private key into this variable encrypts fine, passes every other
     * test, and parks the one secret that must never reach a server in env —
     * undetectably, forever. Caught only here.
     */
    'the private half': RECOVERY.privateKey,
  };
  for (const [label, value] of Object.entries(bad)) {
    // eslint-disable-next-line no-await-in-loop -- see above; the env must hold
    // exactly one value per case.
    await withRecoveryPublic(value, () => {
      assert.throws(() => encryptField(ACCOUNT), (e) => e.code === 'FIELD_ENC_UNAVAILABLE',
        `write with ${label} must throw`);
    });
  }
  // The private-key refusal must say what to do about it, not just refuse.
  await withRecoveryPublic(RECOVERY.privateKey, () => {
    assert.throws(() => encryptField(ACCOUNT),
      (e) => /PRIVATE key/.test(e.message) && /compromised/.test(e.message));
  });

  /*
   * BLANK IS NOT MALFORMED — and .env.example promises exactly this: "if you
   * have already put garbage there, blank the value". A blank (or whitespace)
   * variable is the supported no-recovery-key state and writes unsealed, which
   * is what makes that instruction a real remedy rather than a second outage.
   */
  for (const blank of ['', '   ']) {
    // eslint-disable-next-line no-await-in-loop -- one env value per case.
    await withRecoveryPublic(blank, () => {
      assert.equal(parts(encryptField(ACCOUNT))[2], NO_SEAL);
    });
  }
});

test('a NON-envelope stored value is REFUSED on read, never returned as-is', () => {
  /*
   * This is the plaintext fallback wearing a different hat. If decryptField
   * returned an unrecognised value untouched, one write that bypassed this
   * helper — a manual UPDATE, an import script, a future code path — would put
   * the read path back to serving raw account numbers with every test green.
   */
  for (const stored of [ACCOUNT, 'plain text', 'v3:a:b:c', 'not:an:envelope:at:all']) {
    assert.throws(() => decryptField(stored), (e) => e.code === 'FIELD_ENC_UNAVAILABLE',
      `${stored} must be refused`);
    assert.throws(() => recoverField(stored, RECOVERY.privateKey),
      (e) => e.code === 'FIELD_ENC_UNAVAILABLE', 'the recovery path refuses it too');
  }
});

test('a v1 value is REFUSED — v1 is dropped, not accepted against the current key', () => {
  /*
   * BACKWARD COMPATIBILITY, DECIDED RATHER THAN INHERITED FROM A REGEX.
   *
   * v1 was `v1:<fp>:<iv>:<tag>:<ct>` — one key, no data key, no recovery path.
   * Zero such values exist in any database: the HRMS migrations that create
   * bank_account_number / bank_account_name are all still PENDING and nothing is
   * deployed, so the population is empty today and can never grow. This build is
   * the first that will ever write these columns.
   *
   * Given an empty population, a v1 branch would be a permanently-untestable
   * parse path serving zero rows. Worse, a v1 row has NO SEALED DEK — accepting
   * one means accepting a value with no break-glass path, the exact invariant
   * the write side refuses to break. So: refused, on the same path as any other
   * non-envelope, and pinned here so nobody later "fixes" the regex.
   */
  const p = parts(encryptField(ACCOUNT));
  const v1 = ['v1', p[1], p[7], p[8], p[9]].join(':');
  assert.equal(isEncrypted(v1), false, 'a v1 value is not a v2 envelope');
  assert.throws(() => decryptField(v1), (e) => e.code === 'FIELD_ENC_UNAVAILABLE');
  assert.throws(() => recoverField(v1, RECOVERY.privateKey),
    (e) => e.code === 'FIELD_ENC_UNAVAILABLE');
});

test('a value too long to store encrypted is refused, not silently truncated', () => {
  /*
   * bank_account_number / bank_account_name are VARCHAR(2048) and the envelope
   * carries a fixed 835 characters of overhead before the payload. Outside
   * STRICT mode MySQL TRUNCATES rather than erroring, and an envelope missing
   * its tail fails the GCM tag forever after — an unrecoverable row written by a
   * successful-looking request. The ceiling is enforced in the application so
   * the failure is a 400 at the boundary instead.
   */
  assert.throws(() => encryptField('x'.repeat(4000)),
    (e) => e.status === 400 && e.code === 'FIELD_TOO_LONG');

  // Both real ceilings fit with room to spare, even against a 4096-bit recovery
  // key — the size the owner is told to generate, and the one the VARCHAR width
  // was computed from. Generated once, here, because it is the only test that
  // needs the expensive key.
  const big = newRecoveryKeypair(4096);
  return withRecoveryPublic(big.publicKey, () => {
    const acct = encryptField('9'.repeat(32));
    const name = encryptField('A'.repeat(120));
    assert.equal(acct.length, 879, 'a 32-char account number → 879 of 2048');
    assert.equal(name.length, 995, 'a 120-char ASCII holder name → 995 of 2048');

    // The case that actually stresses the width: 120 CHARACTERS is not 120
    // BYTES. A Devanagari name is 3 bytes per character.
    const devanagari = encryptField('क'.repeat(120));
    assert.equal(devanagari.length, 1315, '120 chars × 3 bytes → 1315 of 2048');

    // And the absolute worst case the 120-char limit permits: 4 bytes each.
    const widest = encryptField('𝄞'.repeat(120));
    assert.equal(widest.length, 1475, '120 chars × 4 bytes → 1475 of 2048');
    assert.ok(widest.length < 2048, 'the column width was chosen from this number');

    // Round-trips, so the assertions above are about length and not a fixture
    // that failed to encrypt.
    assert.equal(decryptField(widest), '𝄞'.repeat(120));
    assert.equal(recoverField(name, big.privateKey), 'A'.repeat(120));
  });
});

// ═══════════════════════════════════════════════════════════════════════
// 3. TAMPERING — THE GCM TAG IS THE POINT, AT EVERY LAYER
// ═══════════════════════════════════════════════════════════════════════

/* Flip one bit of field `i` of an envelope. */
function flipField(envelope, i) {
  const p = parts(envelope);
  const bytes = Buffer.from(p[i], 'base64');
  bytes[0] ^= 0x01;
  p[i] = bytes.toString('base64');
  return p.join(':');
}

test('a tampered VALUE is REJECTED, never decrypted into garbage', () => {
  const ct = encryptField(ACCOUNT);
  for (const [i, what] of [[7, 'iv'], [8, 'tag'], [9, 'ciphertext']]) {
    assert.throws(() => decryptField(flipField(ct, i)),
      (e) => e.code === 'FIELD_DECRYPT_FAILED',
      `an altered value ${what} must throw, not return plausible garbage`);
  }
  // Substitute a whole different IV rather than flipping a bit in one.
  const p = parts(ct);
  p[7] = crypto.randomBytes(12).toString('base64');
  assert.throws(() => decryptField(p.join(':')), (e) => e.code === 'FIELD_DECRYPT_FAILED');

  // And the untouched original still reads, so the assertions above are about
  // the tampering and not a broken fixture.
  assert.equal(decryptField(ct), ACCOUNT);
});

test('a tampered WRAPPED DEK is REJECTED — the key layer is authenticated too', () => {
  /*
   * A malleable data key would be a malleable value: swap the wrapped DEK for
   * one you know and the value decrypts to whatever you like. GCM on the wrap is
   * what stops that, and it is why the wrap is not a bare AES block.
   */
  const ct = encryptField(ACCOUNT);
  for (const [i, what] of [[3, 'dek iv'], [4, 'dek tag'], [5, 'dek ciphertext']]) {
    assert.throws(() => decryptField(flipField(ct, i)),
      (e) => e.code === 'FIELD_DECRYPT_FAILED' && /data key/.test(e.message),
      `an altered ${what} must throw`);
  }
  // Splicing in another row's whole wrapped DEK fails too — it is a valid wrap,
  // but it opens to a DEK that does not match this row's value tag.
  const other = parts(encryptField(HOLDER));
  const p = parts(ct);
  [p[3], p[4], p[5]] = [other[3], other[4], other[5]];
  assert.throws(() => decryptField(p.join(':')), (e) => e.code === 'FIELD_DECRYPT_FAILED');
});

test('a tampered SEALED DEK is REJECTED on the recovery path', () => {
  const ct = encryptField(ACCOUNT);
  assert.throws(() => recoverField(flipField(ct, 6), RECOVERY.privateKey),
    (e) => e.code === 'FIELD_RECOVERY_FAILED',
    'an altered sealed data key must fail RSA-OAEP, not yield a usable key');
  // The NORMAL path is untouched by that damage — the two doors are independent,
  // which is the entire reason there are two.
  assert.equal(decryptField(flipField(ct, 6)), ACCOUNT);
  assert.equal(recoverField(ct, RECOVERY.privateKey), ACCOUNT);
});

test('a forged fingerprint does not become a decryption — the tags still rule', () => {
  /*
   * Both fingerprints are ROUTING hints, never authenticators: they are not in
   * the GCM AAD, so anyone with table access can rewrite them. That is fine, and
   * this test is what makes it fine — restamping a row selects a different key
   * and then fails a tag. The failure mode of a forged stamp is a refusal.
   */
  const keyB = crypto.randomBytes(32).toString('base64');
  const ct = encryptField(ACCOUNT);
  const p = parts(ct);
  p[1] = fpOf(keyB);
  const restamped = p.join(':');
  return withKey(keyB, () => {
    assert.throws(() => decryptField(restamped), (e) => e.code === 'FIELD_DECRYPT_FAILED',
      'a relabelled row must fail the tag, never decrypt');
  });
});

test('the WRONG operational key is a DISTINCT error that names both keys and the way out', () => {
  /*
   * "The tag did not verify" and "I do not hold this key" are the same event to
   * AES-GCM and completely different events to whoever is paged: the first is a
   * corruption hunt, the second is a rotation, and its remedy is either to
   * restore the key or to break-glass. Naming the recovery fingerprint in the
   * same message is what makes the second option actionable at 2am.
   */
  const orphan = encryptField(ACCOUNT);
  const [, orphanOpFp, orphanRecFp] = parts(orphan);
  const keyB = crypto.randomBytes(32).toString('base64');

  return withKey(keyB, () => {
    assert.throws(() => decryptField(orphan), (e) => {
      assert.equal(e.code, 'FIELD_KEY_NOT_IN_RING',
        'NOT FIELD_DECRYPT_FAILED — a missing key is a config fault, not corruption');
      assert.equal(e.status, 500);
      assert.equal(e.fingerprint, orphanOpFp);
      assert.equal(e.activeFingerprint, fpOf(keyB));
      assert.equal(e.recoveryFingerprint, orphanRecFp);
      assert.ok(e.message.includes(orphanOpFp) && e.message.includes(orphanRecFp),
        'both fingerprints in the message, where a log will carry them');
      assert.ok(e.message.includes('field-recover'), 'and the tool that fixes it');
      // No key material, in either encoding, for either key.
      for (const k of [KEY, keyB]) {
        assert.equal(e.message.includes(k), false, 'no base64 key in the message');
        assert.equal(e.message.includes(Buffer.from(k, 'base64').toString('hex')), false,
          'no hex key in the message');
      }
      return true;
    });
    // The recovery path is COMPLETELY unaffected by the operational key being
    // wrong. That is the promise.
    assert.equal(recoverField(orphan, RECOVERY.privateKey), ACCOUNT);
  });
});

// ═══════════════════════════════════════════════════════════════════════
// 4. BREAK GLASS
// ═══════════════════════════════════════════════════════════════════════

test('RECOVERY DECRYPTS WITH ONLY THE PRIVATE KEY — the operational key absent entirely', async () => {
  /*
   * The headline property. If this test is red, the recovery key is decoration
   * and the owner's premise — "at least users with the master key will be able
   * to fetch all the details if something goes wrong with the main key" — is
   * false.
   */
  const ct = encryptField(ACCOUNT);
  const name = encryptField(HOLDER);

  await withKey(undefined, () => {
    assert.throws(() => decryptField(ct), (e) => e.code === 'FIELD_ENC_UNAVAILABLE',
      'the normal path is dead');
    assert.equal(recoverField(ct, RECOVERY.privateKey), ACCOUNT, 'the recovery path is not');
    assert.equal(recoverField(name, RECOVERY.privateKey), HOLDER);
  });
  // …and with a WRONG operational key, which is the likelier incident: someone
  // rotated and lost the old value.
  await withKey(crypto.randomBytes(32).toString('base64'), () => {
    assert.throws(() => decryptField(ct), (e) => e.code === 'FIELD_KEY_NOT_IN_RING');
    assert.equal(recoverField(ct, RECOVERY.privateKey), ACCOUNT);
  });
});

test('the WRONG recovery private key is a distinct error naming both fingerprints', () => {
  const other = newRecoveryKeypair();
  const ct = encryptField(ACCOUNT);
  assert.throws(() => recoverField(ct, other.privateKey), (e) => {
    assert.equal(e.code, 'FIELD_RECOVERY_KEY_MISMATCH',
      'NOT FIELD_RECOVERY_FAILED — "wrong key from your notes" is not "the row is damaged"');
    assert.equal(e.fingerprint, fpOfPublic(RECOVERY.publicKey), 'the key the row wants');
    assert.equal(e.suppliedFingerprint, fpOfPublic(other.publicKey), 'the key you brought');
    // The private key must not appear anywhere near the error.
    assert.equal(e.message.includes('PRIVATE'), false);
    assert.equal(e.message.includes(other.privateKey.split('\n')[1]), false);
    return true;
  });
});

test('a garbage private key is refused without leaking what was passed', () => {
  const ct = encryptField(ACCOUNT);
  assert.throws(() => recoverField(ct, 'not a pem at all'),
    (e) => e.code === 'FIELD_RECOVERY_FAILED');
  assert.throws(() => recoverField(ct, RECOVERY.publicKey),
    // The PUBLIC half is not a private key, and is a very easy paste to make.
    (e) => e.code === 'FIELD_RECOVERY_FAILED');
});

// ═══════════════════════════════════════════════════════════════════════
// 5. RE-KEYING — THE VALUE CIPHERTEXT NEVER MOVES
// ═══════════════════════════════════════════════════════════════════════

test('rewrapToOperationalKey re-keys with the CURRENT key in hand, value untouched', () => {
  const keyB = crypto.randomBytes(32).toString('base64');
  const before = encryptField(ACCOUNT);
  const after = rewrapToOperationalKey(before, keyB, { currentKey: KEY });

  assert.equal(valueCiphertext(after), valueCiphertext(before),
    'THE property: the value ciphertext is byte-identical');
  assert.equal(parts(after)[6], parts(before)[6], 'the sealed data key is untouched too');
  assert.equal(parts(after)[2], parts(before)[2], 'and so is the recovery fingerprint');
  assert.equal(parts(after)[1], fpOf(keyB), 'only the operational fingerprint moved');
  assert.notEqual(parts(after)[5], parts(before)[5], 'and the wrapped data key under it');

  return withKey(keyB, () => {
    assert.equal(decryptField(after), ACCOUNT, 'the new key opens it');
    assert.equal(recoverField(after, RECOVERY.privateKey), ACCOUNT,
      'and break-glass still works afterwards — the door was not closed by the repair');
  });
});

test('rewrapToOperationalKey re-keys via the RECOVERY key when the old key is GONE', () => {
  /*
   * The repair for a LOST operational key. Nothing is re-encrypted, so a bulk
   * job that dies halfway has damaged nothing and can simply be re-run.
   */
  const keyB = crypto.randomBytes(32).toString('base64');
  const before = encryptField(ACCOUNT);
  const after = rewrapToOperationalKey(before, keyB, { recoveryPrivateKey: RECOVERY.privateKey });

  assert.equal(valueCiphertext(after), valueCiphertext(before));
  return withKey(keyB, () => assert.equal(decryptField(after), ACCOUNT));
});

test('rewrapField is the CLI path: re-wrap under the CURRENT env key via recovery', async () => {
  const keyB = crypto.randomBytes(32).toString('base64');
  const before = encryptField(ACCOUNT);   // under KEY
  // The operational key is rotated to B and the old one is gone.
  await withKey(keyB, () => {
    assert.throws(() => decryptField(before), (e) => e.code === 'FIELD_KEY_NOT_IN_RING');
    const after = rewrapField(before, RECOVERY.privateKey);
    assert.equal(valueCiphertext(after), valueCiphertext(before));
    assert.equal(decryptField(after), ACCOUNT, 'readable on the normal path again');
  });
});

test('rewrapToOperationalKey REFUSES the wrong current key rather than writing a broken row', () => {
  const before = encryptField(ACCOUNT);
  assert.throws(
    () => rewrapToOperationalKey(before, crypto.randomBytes(32).toString('base64'),
      { currentKey: crypto.randomBytes(32).toString('base64') }),
    (e) => e.code === 'FIELD_KEY_NOT_IN_RING',
  );
  // And it needs to be told HOW to open the envelope at all.
  assert.throws(() => rewrapToOperationalKey(before, crypto.randomBytes(32).toString('base64'), {}),
    (e) => e.code === 'FIELD_ENC_UNAVAILABLE');
});

test('resealToRecoveryKey replaces a LEAKED recovery key, value and wrap untouched', () => {
  /*
   * The answer to a leaked recovery key: unseal each data key with the OLD
   * private half and re-seal it to the NEW public one. Afterwards the leaked key
   * is worthless.
   *
   * ⚠ This needs the old key. A recovery key that was LOST rather than leaked
   *   cannot be re-sealed away — existing rows keep no break-glass path. The
   *   data is NOT lost; the operational key still reads it perfectly. That
   *   distinction has to reach the operator, and it is the reason this test
   *   exists next to the one above it.
   */
  const next = newRecoveryKeypair();
  const before = encryptField(ACCOUNT);
  const after = resealToRecoveryKey(before, next.publicKey,
    { recoveryPrivateKey: RECOVERY.privateKey });

  assert.equal(valueCiphertext(after), valueCiphertext(before),
    'THE property: the value ciphertext is byte-identical');
  assert.equal(parts(after)[1], parts(before)[1], 'the operational fingerprint is untouched');
  assert.equal(parts(after).slice(3, 6).join(':'), parts(before).slice(3, 6).join(':'),
    'and so is the whole wrapped data key — a re-seal cannot break a normal read');
  assert.equal(parts(after)[2], fpOfPublic(next.publicKey), 'only the recovery fingerprint moved');

  assert.equal(decryptField(after), ACCOUNT, 'the normal path is unaffected');
  assert.equal(recoverField(after, next.privateKey), ACCOUNT, 'the NEW recovery key opens it');
  assert.throws(() => recoverField(after, RECOVERY.privateKey),
    (e) => e.code === 'FIELD_RECOVERY_KEY_MISMATCH',
    'and the leaked one no longer does');
});

test('resealToRecoveryKey refuses without the OLD private key, and refuses a weak new key', () => {
  const before = encryptField(ACCOUNT);
  const next = newRecoveryKeypair();
  assert.throws(() => resealToRecoveryKey(before, next.publicKey, {}),
    (e) => e.code === 'FIELD_ENC_UNAVAILABLE' && /recoveryPrivateKey/.test(e.message));
  assert.throws(
    () => resealToRecoveryKey(before, newRecoveryKeypair(1024).publicKey,
      { recoveryPrivateKey: RECOVERY.privateKey }),
    (e) => e.code === 'FIELD_ENC_UNAVAILABLE' && /1024/.test(e.message),
  );
});

test('both re-key primitives are IDEMPOTENT-SAFE: the value ciphertext survives a chain', () => {
  /*
   * The bulk flows will run these repeatedly, possibly over rows a previous
   * interrupted run already touched. After an operational rotation, a recovery
   * re-seal, and a second operational rotation, the value ciphertext must still
   * be the bytes the original encrypt produced — otherwise "safe to interrupt"
   * is not true and a half-finished job is a half-corrupted column.
   */
  const original = encryptField(ACCOUNT);
  const keyB = crypto.randomBytes(32).toString('base64');
  const keyC = crypto.randomBytes(32).toString('base64');
  const rec2 = newRecoveryKeypair();

  const a = rewrapToOperationalKey(original, keyB, { currentKey: KEY });
  const b = resealToRecoveryKey(a, rec2.publicKey, { recoveryPrivateKey: RECOVERY.privateKey });
  const c = rewrapToOperationalKey(b, keyC, { recoveryPrivateKey: rec2.privateKey });

  for (const [label, env] of [['rotate', a], ['reseal', b], ['rotate again', c]]) {
    assert.equal(valueCiphertext(env), valueCiphertext(original), `unchanged after ${label}`);
  }
  return withKey(keyC, () => {
    assert.equal(decryptField(c), ACCOUNT);
    assert.equal(recoverField(c, rec2.privateKey), ACCOUNT);
  });
});

test('a re-key refuses a non-envelope rather than inventing one', () => {
  for (const junk of [ACCOUNT, 'v1:aa:bb:cc:dd', '', null]) {
    assert.throws(() => rewrapToOperationalKey(junk, KEY, { currentKey: KEY }),
      (e) => e.code === 'FIELD_ENC_UNAVAILABLE');
    assert.throws(() => resealToRecoveryKey(junk, RECOVERY.publicKey,
      { recoveryPrivateKey: RECOVERY.privateKey }), (e) => e.code === 'FIELD_ENC_UNAVAILABLE');
    assert.throws(() => sealToRecoveryKey(junk, RECOVERY.publicKey),
      (e) => e.code === 'FIELD_ENC_UNAVAILABLE');
  }
});

// ═══════════════════════════════════════════════════════════════════════
// 5b. THE ONE-KEY LIFECYCLE — what the owner will actually do
// ═══════════════════════════════════════════════════════════════════════
/*
 * These four are the change. Everything above says the unsealed envelope is
 * well-formed; these say it is LIVEABLE — that the operations an owner running
 * on one key will actually perform work on it, and that the one operation that
 * CANNOT work says so clearly instead of failing somewhere inside RSA.
 */

/* An envelope written with no recovery key configured. */
async function unsealedEnvelope(value = ACCOUNT) {
  let out;
  await withRecoveryPublic(undefined, () => { out = encryptField(value); });
  return out;
}

test('ROTATE WORKS WITH NO RECOVERY KEY — the mode this deployment actually uses', async () => {
  /*
   * The operational key is the only key in this system, so rotating it is the
   * only key operation that will ever be run — and it must not need the thing
   * that is not configured. The seal fields are copied through as they are: the
   * sentinel stays a sentinel, the empty seal stays empty, and the result is a
   * valid envelope that reads on the new key.
   */
  const before = await unsealedEnvelope();
  const newKey = crypto.randomBytes(32).toString('base64');

  const after = rewrapToOperationalKey(before, newKey, { currentKey: KEY });

  assert.equal(parts(after)[1], fpOf(newKey), 'the wrap moved to the new key');
  assert.equal(parts(after)[2], NO_SEAL, 'and the row is still, honestly, unsealed');
  assert.equal(parts(after)[6], '', 'with the seal field still empty, not invented');
  assert.equal(isEncrypted(after), true, 'the result is a well-formed envelope');
  assert.equal(valueCiphertext(after), valueCiphertext(before),
    'and the value ciphertext is byte identical, as in every other re-key');

  await withKey(newKey, () => {
    assert.equal(decryptField(after), ACCOUNT, 'the new key reads it');
  });
  // The whole point of a rotation: the OLD key no longer opens it. And the
  // error must not send anyone hunting for a break-glass key that was never
  // created — "the recovery key -" is not an instruction.
  assert.throws(() => decryptField(after), (e) => {
    assert.equal(e.code, 'FIELD_KEY_NOT_IN_RING');
    assert.match(e.message, /NO recovery key/, 'it says there is no second door');
    assert.equal(e.message.includes(`recovery key ${NO_SEAL}`), false);
    return true;
  });
});

test('RECOVER REFUSES an unsealed row with its own code, not a confusing crypto failure', async () => {
  /*
   * There is no sealed data key, so no private key on earth opens this row. The
   * remedy is completely different from every other recovery failure — it is
   * "you cannot do this at all", not "wrong key" — so it gets its own code and
   * a message that names the reason and the way forward.
   */
  const unsealed = await unsealedEnvelope();
  const kp = newRecoveryKeypair();

  for (const [what, fn] of [
    ['recoverField', () => recoverField(unsealed, kp.privateKey)],
    ['break-glass rewrap', () => rewrapToOperationalKey(unsealed, KEY, { recoveryPrivateKey: kp.privateKey })],
    ['reseal', () => resealToRecoveryKey(unsealed, kp.publicKey, { recoveryPrivateKey: kp.privateKey })],
  ]) {
    assert.throws(fn, (e) => {
      assert.equal(e.code, 'FIELD_NOT_SEALED', `${what} must use the distinct code`);
      assert.match(e.message, /no recovery key configured/i, 'and say WHY');
      assert.match(e.message, /sealToRecoveryKey/, 'and say what to do instead');
      return true;
    }, what);
  }

  // Not merely "an error" — it must not be the WRONG-KEY error, which would send
  // an operator hunting through their notes for a key that would not have helped.
  assert.throws(() => recoverField(unsealed, kp.privateKey),
    (e) => e.code !== 'FIELD_RECOVERY_KEY_MISMATCH');
});

test('AN UNSEALED ROW CAN BE SEALED LATER, with ONLY the operational key', async () => {
  /*
   * The good news in this design, and the reason "no recovery key today" is not
   * a one-way door: registering a keypair next year retro-protects everything
   * written this year. No old private key is involved because there is no old
   * seal to open — the operational key unwraps the data key and it is sealed to
   * the new public half.
   */
  const unsealed = await unsealedEnvelope();
  const later = newRecoveryKeypair();

  const sealed = sealToRecoveryKey(unsealed, later.publicKey);

  assert.equal(parts(sealed)[2], fpOfPublic(later.publicKey), 'the row now names the new key');
  assert.equal(parts(sealed)[1], parts(unsealed)[1], 'the operational wrap is untouched…');
  assert.deepEqual(parts(sealed).slice(3, 6), parts(unsealed).slice(3, 6), '…byte for byte');
  assert.equal(valueCiphertext(sealed), valueCiphertext(unsealed),
    'and the value ciphertext never moved');

  // BOTH doors now open it — which is the entire claim.
  assert.equal(decryptField(sealed), ACCOUNT, 'the operational key still reads it');
  assert.equal(recoverField(sealed, later.privateKey), ACCOUNT, 'and break-glass works now');

  // What it needs, stated as a test: a WORKING operational key. A row wrapped
  // under a key nobody holds cannot be sealed — retro-protection is a door you
  // open while you can still read the data, not after the fire.
  const stranger = crypto.randomBytes(32).toString('base64');
  assert.throws(() => sealToRecoveryKey(unsealed, later.publicKey, { operationalKey: stranger }),
    (e) => e.code === 'FIELD_KEY_NOT_IN_RING');
});

test('seal and reseal refuse each other’s rows — two operations, not one with a flag', () => {
  /*
   * Sealing a row that has none and REPLACING the seal on a row that has one
   * take different keys and answer different incidents. Confusing them at 2am is
   * how a leaked recovery key gets left in place, so each refuses the other's
   * input by name rather than doing something plausible.
   */
  const sealed = encryptField(ACCOUNT);          // sealed to RECOVERY, from env
  const fresh = newRecoveryKeypair();

  assert.throws(() => sealToRecoveryKey(sealed, fresh.publicKey), (e) => {
    assert.equal(e.code, 'FIELD_ENC_UNAVAILABLE');
    assert.match(e.message, /already sealed/, 'it names the state it found');
    assert.match(e.message, /resealToRecoveryKey/, 'and points at the right function');
    return true;
  });

  // And the working reseal still works — this did not narrow it.
  const moved = resealToRecoveryKey(sealed, fresh.publicKey, { recoveryPrivateKey: RECOVERY.privateKey });
  assert.equal(parts(moved)[2], fpOfPublic(fresh.publicKey));
  assert.equal(recoverField(moved, fresh.privateKey), ACCOUNT);
});

// ═══════════════════════════════════════════════════════════════════════
// 6. WHERE THE RECOVERY KEY COMES FROM — DATABASE, THEN ENV, THEN NOTHING
// ═══════════════════════════════════════════════════════════════════════

test('a STORED recovery key wins over env — rotation without a deploy', async () => {
  const stored = newRecoveryKeypair();
  const rows = [{
    fingerprint: fpOfPublic(stored.publicKey),
    public_key: stored.publicKey,
    active: true,
  }];

  const desc = await resolveRecoveryPublicKey(store(rows));
  try {
    assert.deepEqual(desc, { fingerprint: fpOfPublic(stored.publicKey), source: 'database' });
    // No key material in the descriptor — it is meant to be logged at boot.
    assert.equal(JSON.stringify(desc).includes('BEGIN'), false);

    const ct = encryptField(ACCOUNT);
    assert.equal(parts(ct)[2], fpOfPublic(stored.publicKey), 'writes seal to the STORED key');
    assert.equal(recoverField(ct, stored.privateKey), ACCOUNT);
    assert.throws(() => recoverField(ct, RECOVERY.privateKey),
      (e) => e.code === 'FIELD_RECOVERY_KEY_MISMATCH', 'and not to the env one');
  } finally {
    await resetRecoveryToEnv();
  }
});

test('an EMPTY store falls back to env, and clears a previously primed key', async () => {
  const stored = newRecoveryKeypair();
  await resolveRecoveryPublicKey(store([{ public_key: stored.publicKey, active: true }]));
  try {
    assert.equal(parts(encryptField(ACCOUNT))[2], fpOfPublic(stored.publicKey));

    // The row is deleted. A stale cache would keep sealing to a key that is no
    // longer the active one and that nobody is looking after any more.
    const desc = await resolveRecoveryPublicKey(store([]));
    assert.equal(desc.source, 'env');
    assert.equal(parts(encryptField(ACCOUNT))[2], fpOfPublic(RECOVERY.publicKey));
  } finally {
    await resetRecoveryToEnv();
  }
});

test("NO store row and NO env resolves to source 'none' — the boot log must not cry wolf", async () => {
  /*
   * The descriptor is what server.js logs. It has to be able to say "no recovery
   * key is configured" as a STATEMENT OF FACT at info, because that is the
   * chosen configuration and a warning on every boot teaches everyone to ignore
   * warnings. A throw here would force the boot path to treat the normal state
   * as an error — which is exactly what it used to do.
   */
  await withRecoveryPublic(undefined, async () => {
    const desc = await resolveRecoveryPublicKey(store([]));
    assert.deepEqual(desc, { fingerprint: null, source: 'none' });
    // And writes carry on, unsealed.
    assert.equal(parts(encryptField(ACCOUNT))[2], NO_SEAL);
  });
  await resetRecoveryToEnv();
});

test('a CONFIGURED-but-broken store key still REJECTS — that is what keeps warn meaningful', async () => {
  // The other half of the boot-log split: source 'none' is info, a throw is
  // warn, and only a key someone actually configured can produce the throw.
  await withRecoveryPublic(undefined, async () => {
    await assert.rejects(() => resolveRecoveryPublicKey(store([{ public_key: 'not a key', active: true }])),
      (e) => e.code === 'FIELD_ENC_UNAVAILABLE');
  });
  await resetRecoveryToEnv();
});

test('a store row whose claimed fingerprint disagrees with its key is REFUSED', async () => {
  /*
   * The fingerprint is derived, but another writer owns that table and will put
   * a fingerprint column in it. The moment an id is STORED rather than computed,
   * it can disagree with the key it names — and every error message built on it
   * becomes a lie at the exact moment someone is trusting it. So it is checked,
   * not trusted.
   */
  const stored = newRecoveryKeypair();
  const rows = [{ fingerprint: 'deadbeef', public_key: stored.publicKey, active: true }];
  await assert.rejects(() => resolveRecoveryPublicKey(store(rows)), (e) => {
    assert.equal(e.code, 'FIELD_ENC_UNAVAILABLE');
    assert.ok(e.message.includes('deadbeef') && e.message.includes(fpOfPublic(stored.publicKey)));
    return true;
  });
  await resetRecoveryToEnv();
});

test('a store row with a weak or wrong-type key is REFUSED', async () => {
  for (const bad of [newRecoveryKeypair(1024).publicKey, 'not a key']) {
    // eslint-disable-next-line no-await-in-loop -- one store state per case.
    await assert.rejects(() => resolveRecoveryPublicKey(store([{ public_key: bad, active: true }])),
      (e) => e.code === 'FIELD_ENC_UNAVAILABLE');
  }
  await resetRecoveryToEnv();
});

test('recoveryKeyByFingerprint turns a rec_fp into something an operator recognises', async () => {
  const stored = newRecoveryKeypair();
  const fp = fpOfPublic(stored.publicKey);
  const rows = [{
    fingerprint: fp, public_key: stored.publicKey, active: false, label: 'notes-2026-03',
  }];
  const runner = store(rows);

  const found = await recoveryKeyByFingerprint(fp, runner);
  assert.equal(found.fp, fp);
  assert.equal(found.row.label, 'notes-2026-03', 'the store row comes back for display');
  assert.equal(await recoveryKeyByFingerprint('00000000', runner), null,
    'an unknown fingerprint is null, not a throw — "I do not know that key" is an answer');
  assert.equal(await recoveryKeyByFingerprint(fp, null), null, 'and no store is not a crash');
});

// ═══════════════════════════════════════════════════════════════════════
// 7. THE MASKS
// ═══════════════════════════════════════════════════════════════════════

test('maskAccountNumber shows four digits and a FIXED number of bullets', () => {
  assert.equal(maskAccountNumber('6789'), '••••6789');
  // Given a full number it uses the tail — and the output length does not
  // reveal how long the number was, which would itself hint at the bank.
  assert.equal(maskAccountNumber(ACCOUNT), '••••6789');
  assert.equal(maskAccountNumber('123456789012345678'), '••••5678');
  assert.equal(maskAccountNumber(null), null);
  assert.equal(maskAccountNumber(''), null);
});

test('maskName keeps one initial per part and hides the rest', () => {
  assert.equal(maskName(HOLDER), 'P•••• S••••');
  assert.equal(maskName('Anita Kumari Rao'), 'A•••• K•••• R••••');
  assert.equal(maskName('Ravi'), 'R••••');
  assert.equal(maskName('  Ravi   Kumar  '), 'R•••• K••••');
  assert.equal(maskName(null), null);
  // Fixed-width bullets: two names of very different length mask identically,
  // so the mask does not leak the name's length.
  assert.equal(maskName('Al Bo'), maskName('Alexandra Bornstein'));
});

test('neither mask ever emits the input value or a ciphertext', () => {
  const masked = maskAccountNumber(ACCOUNT) + ' ' + maskName(HOLDER);
  assert.equal(masked.includes(ACCOUNT), false);
  assert.equal(masked.includes(HOLDER), false);
  assert.equal(masked.includes('Sharma'), false);
  // A ciphertext is not a display value: '••••cGVy' would look like a masked
  // account number and be entirely meaningless.
  const ct = encryptField(ACCOUNT);
  assert.throws(() => maskAccountNumber(ct), (e) => e.code === 'FIELD_ENC_UNAVAILABLE');
  assert.throws(() => maskName(ct), (e) => e.code === 'FIELD_ENC_UNAVAILABLE');
});
