-- Remove the retired per-person mailbox-provisioning allowlist (2026-08-03).
--
-- WHAT THIS KEY DID
-- easyfix_properties['access.entraprovision.emails'] held a comma-separated list
-- of operator emails permitted to trigger Microsoft 365 mailbox provisioning. It
-- was read by services/feature-access.service.js as FEATURES.canProvisionMailboxes
-- and enforced on BOTH POST /api/admin/users (Add User) and
-- POST /api/admin/users/:userId/provision-mailbox (the repair endpoint).
--
-- WHY IT IS BEING REMOVED, not merely populated
-- 1. WRONG BOUNDARY. Creating the mailbox is part of creating a staff user, not
--    a separate privilege. Whoever is trusted to create the CRM account (already
--    gated by roleByName(['Admin'])) is trusted to create its mailbox. Splitting
--    the two only ever half-creates a person.
-- 2. IT FAILED CLOSED AND SILENTLY. emailAllowed() returns false for an UNSET
--    property, and this key was never populated in production — so EVERY Add
--    User recorded account_status='skipped_not_allowed' and no mailbox was ever
--    created. Observed on user_id 8735 (vijay.nailwal@easyfix.in, 2026-08-03):
--    tbl_user row created, Entra account absent, discovered only when the user
--    could not log in. The same empty list also gated the repair endpoint the
--    error message told operators to use, so the recovery path was deadlocked
--    too. A gate whose default is "nobody" turns an opt-in feature into a
--    permanent no-op.
--
-- WHAT STILL GATES PROVISIONING (unchanged, and sufficient)
--   * roleByName(['Admin']) on both routes — who may act.
--   * easyfix_properties['entra.provisioning.enabled'] (default 'false') — the
--     master switch, still fail-closed, which is correct for a switch.
--   * entra.managed.domains — only addresses in a domain we own.
--   * The Graph app registration's admin-consented permissions.
--
-- ⚠ HISTORICAL DATA IS NOT TOUCHED. Rows in tbl_user_entra_provisioning that
-- carry account_status='skipped_not_allowed' are left exactly as they are: they
-- are the audit trail of what happened, and the status stays in the service's
-- vocabulary so those rows remain readable. Nothing writes that status any more.
-- Re-run the repair endpoint for each affected user to provision them:
--     POST /api/admin/users/<user_id>/provision-mailbox
-- Find them with:
--     SELECT user_id, user_principal_name, created_on
--       FROM tbl_user_entra_provisioning
--      WHERE account_status = 'skipped_not_allowed';
--
-- NOTE FOR verify:migrations — this is a DATA-ONLY migration (a DELETE), so the
-- checker reports it as UNKNOWN rather than applied. That is by design: it
-- refuses to infer "applied" from an absence, because a false pass is worse than
-- no answer. Confirm by hand with the SELECT below.
--
-- Idempotent: deleting an already-absent row affects 0 rows and is safe to
-- re-run. No schema change.

DELETE FROM easyfix_properties WHERE property_key = 'access.entraprovision.emails';

-- Verification (expect 0 rows):
-- SELECT * FROM easyfix_properties WHERE property_key = 'access.entraprovision.emails';
