const PDFDocument = require('pdfkit');

/*
 * EasyFix client invoice PDF.
 *
 * Inputs:
 *   invoice  — tbl_client_invoice row (id, invoice_number, invoice_date,
 *              billing_from_date, billing_to_date, total_invoice_amount,
 *              total_paid_amount, total_tds_deducted, current_due_amount,
 *              previous_due_amount, invoice_desc)
 *   client   — { client_name, client_address?, gstin? } from tbl_client
 *   lines    — flat per-service line items: { job_id, job_ref, customer,
 *              service, quantity, unit_charge, material, line_total }
 *   stream   — writable; doc is piped here. For HTTP this is `res`.
 *
 * Mirrors the legacy iText `InvoiceApprovalPDF.java` artifact shape — header,
 * client/billing block, line-item table, totals footer. Light styling
 * matches the Excel master sheet so both artifacts read consistently.
 */
function renderInvoicePdf({ invoice, client, lines, stream }) {
  const doc = new PDFDocument({ size: 'A4', margin: 40 });
  doc.pipe(stream);

  // Header
  doc.font('Helvetica-Bold').fontSize(20).text('EasyFix', { align: 'left' });
  doc.fontSize(10).font('Helvetica').text('Tax Invoice', { align: 'left' });
  doc.moveDown(0.5);

  // Invoice meta — right side
  const top = doc.y;
  doc.font('Helvetica-Bold').fontSize(10).text(`Invoice #: ${invoice.invoice_number || invoice.id}`, 350, top);
  doc.font('Helvetica').fontSize(9);
  doc.text(`Date: ${formatDate(invoice.invoice_date)}`, 350);
  doc.text(`Billing Period: ${formatDate(invoice.billing_from_date)} – ${formatDate(invoice.billing_to_date)}`, 350);

  // Client block
  doc.moveDown(1.5);
  doc.font('Helvetica-Bold').fontSize(11).text('Bill To');
  doc.font('Helvetica').fontSize(10).text(client.client_name || '—');
  if (client.client_address) doc.text(String(client.client_address));
  if (client.gstin)          doc.text(`GSTIN: ${client.gstin}`);

  doc.moveDown(1);
  if (invoice.invoice_desc) {
    doc.font('Helvetica-Oblique').fontSize(9).text(String(invoice.invoice_desc));
    doc.moveDown(0.5);
  }

  // Line items table
  const tableTop = doc.y;
  const cols = [
    { key: 'job_ref',     label: 'Job Ref', x: 40,  w: 65 },
    { key: 'customer',    label: 'Customer', x: 105, w: 100 },
    { key: 'service',     label: 'Service',  x: 205, w: 175 },
    { key: 'quantity',    label: 'Qty',      x: 380, w: 30, align: 'right' },
    { key: 'unit_charge', label: 'Unit',     x: 410, w: 50, align: 'right' },
    { key: 'material',    label: 'Material', x: 460, w: 45, align: 'right' },
    { key: 'line_total',  label: 'Total',    x: 505, w: 55, align: 'right' },
  ];

  // Header row
  doc.font('Helvetica-Bold').fontSize(9);
  cols.forEach((c) => doc.text(c.label, c.x, tableTop, { width: c.w, align: c.align || 'left' }));
  doc.moveTo(40, tableTop + 12).lineTo(560, tableTop + 12).stroke();

  // Data rows
  doc.font('Helvetica').fontSize(8);
  let y = tableTop + 16;
  let subtotal = 0;
  for (const row of lines) {
    if (y > 770) { doc.addPage(); y = 40; }
    cols.forEach((c) => {
      const v = row[c.key];
      const text = v == null ? '' : (typeof v === 'number' ? v.toFixed(2) : String(v));
      doc.text(text, c.x, y, { width: c.w, align: c.align || 'left' });
    });
    subtotal += Number(row.line_total || 0);
    y += 14;
  }

  // Totals footer
  y += 8;
  doc.moveTo(380, y).lineTo(560, y).stroke();
  y += 6;
  doc.font('Helvetica-Bold').fontSize(9);
  const totalAmount = Number(invoice.total_invoice_amount || subtotal);
  const previous = Number(invoice.previous_due_amount || 0);
  const paid = Number(invoice.total_paid_amount || 0);
  const tds = Number(invoice.total_tds_deducted || 0);
  const dueNow = Number(invoice.current_due_amount || (totalAmount - paid - tds));

  const writeRow = (label, val) => {
    doc.text(label, 380, y, { width: 110, align: 'right' });
    doc.text(val.toFixed(2), 495, y, { width: 65, align: 'right' });
    y += 12;
  };
  writeRow('Subtotal', subtotal);
  if (previous) writeRow('Previous Due', previous);
  writeRow('Invoice Amount', totalAmount);
  if (paid) writeRow('Paid', -paid);
  if (tds) writeRow('TDS Deducted', -tds);
  doc.moveTo(380, y).lineTo(560, y).stroke();
  y += 4;
  doc.fontSize(10);
  writeRow('Amount Due', dueNow);

  // Footer
  doc.font('Helvetica').fontSize(8).fillColor('gray');
  doc.text('Generated by EasyFix CRM.  This is a computer-generated invoice and does not require a signature.',
    40, 800, { width: 520, align: 'center' });

  doc.end();
}

function formatDate(d) {
  if (!d) return '—';
  const date = d instanceof Date ? d : new Date(d);
  if (isNaN(date)) return String(d);
  const pad = (n) => String(n).padStart(2, '0');
  return `${pad(date.getDate())}-${pad(date.getMonth() + 1)}-${date.getFullYear()}`;
}

module.exports = { renderInvoicePdf };
